language: node_js
node_js:
  - '8'
services:
  - redis-server
before_install:
  - 'if [[ `npm -v` != 6* ]]; then npm i -g npm@6; fi'
  - npm cache verify
script: npm run ci
conditions:
  'branch:master': npm test
  default: npm test
